/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { workspaceDocumentsGetWorkspaceDocumentContents } from "../../funcs/workspaceDocumentsGetWorkspaceDocumentContents.js";
import * as operations from "../../models/operations/index.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: operations.GetWorkspaceDocumentContentsRequest$inboundSchema,
};

export const tool$workspaceDocumentsGetWorkspaceDocumentContents:
  ToolDefinition<typeof args> = {
    name: "workspace-documents-get-workspace-document-contents",
    description: `Get the file contents of the document

This operation retrieves the file contents of the document. The file is returned as a stream in the response body. The Content-Disposition response header contains the document name as the \`filename\`.`,
    args,
    tool: async (client, args, ctx) => {
      const [result, apiCall] =
        await workspaceDocumentsGetWorkspaceDocumentContents(
          client,
          args.request,
          { fetchOptions: { signal: ctx.signal } },
        ).$inspect();

      if (!result.ok) {
        return {
          content: [{ type: "text", text: result.error.message }],
          isError: true,
        };
      }

      const value = result.value;

      return formatResult(value, apiCall);
    },
  };
