/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { workspacesGetWorkspaceEnvelopes } from "../../funcs/workspacesGetWorkspaceEnvelopes.js";
import * as operations from "../../models/operations/index.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: operations.GetWorkspaceEnvelopesRequest$inboundSchema,
};

export const tool$workspacesGetWorkspaceEnvelopes: ToolDefinition<typeof args> =
  {
    name: "workspaces-get-workspace-envelopes",
    description: `Returns the envelopes associated with the given workspace

This operation retrieves a list of all associated workspace envelopes. The \`status\` on each envelope can be used to track envelope progress. Based on the permissions of the caller, additional envelope details may be retrieved from the eSignature API using the \`envelope_id\`.`,
    args,
    tool: async (client, args, ctx) => {
      const [result, apiCall] = await workspacesGetWorkspaceEnvelopes(
        client,
        args.request,
        { fetchOptions: { signal: ctx.signal } },
      ).$inspect();

      if (!result.ok) {
        return {
          content: [{ type: "text", text: result.error.message }],
          isError: true,
        };
      }

      const value = result.value;

      return formatResult(value, apiCall);
    },
  };
