/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { workspaceDocumentsDeleteWorkspaceDocument } from "../../funcs/workspaceDocumentsDeleteWorkspaceDocument.js";
import * as operations from "../../models/operations/index.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: operations.DeleteWorkspaceDocumentRequest$inboundSchema,
};

export const tool$workspaceDocumentsDeleteWorkspaceDocument: ToolDefinition<
  typeof args
> = {
  name: "workspace-documents-delete-workspace-document",
  description: `Deletes a document in the workspace

This operation permanently deletes a document by ID.`,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await workspaceDocumentsDeleteWorkspaceDocument(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    return formatResult(void 0, apiCall);
  },
};
