/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { workspacesGetWorkspace } from "../../funcs/workspacesGetWorkspace.js";
import * as operations from "../../models/operations/index.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: operations.GetWorkspaceRequest$inboundSchema,
};

export const tool$workspacesGetWorkspace: ToolDefinition<typeof args> = {
  name: "workspaces-get-workspace",
  description: `Returns details about the workspace

This operation retrieves details about a specific workspace. It returns the workspace's unique identifier (ID), name, and metadata such as when it was created and by whom.`,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await workspacesGetWorkspace(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
