/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { workspacesCreateWorkspace } from "../../funcs/workspacesCreateWorkspace.js";
import * as operations from "../../models/operations/index.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: operations.CreateWorkspaceRequest$inboundSchema,
};

export const tool$workspacesCreateWorkspace: ToolDefinition<typeof args> = {
  name: "workspaces-create-workspace",
  description: `Creates a new workspace

This operation creates a new workspace. The calling user is automatically added as a member of the workspace with the role of Manage.

Once created, the \`workspace_id\` is utilized to associate tasks such as envelopes. Participants on tasks will automatically be added to the workspace with the Participate role.`,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await workspacesCreateWorkspace(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
