/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { workspaceUsersRevokeWorkspaceUserAccess } from "../../funcs/workspaceUsersRevokeWorkspaceUserAccess.js";
import * as operations from "../../models/operations/index.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: operations.RevokeWorkspaceUserAccessRequest$inboundSchema,
};

export const tool$workspaceUsersRevokeWorkspaceUserAccess: ToolDefinition<
  typeof args
> = {
  name: "workspace-users-revoke-workspace-user-access",
  description: `Revokes the specified user's access to the workspace

This operation revokes the specified user's access to the workspace. The optional \`revocation_date\` may be set to schedule revocation in the future. If not specified, the revocation will be immediate.`,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await workspaceUsersRevokeWorkspaceUserAccess(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    return formatResult(void 0, apiCall);
  },
};
