/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { workspaceDocumentsGetWorkspaceDocument } from "../../funcs/workspaceDocumentsGetWorkspaceDocument.js";
import * as operations from "../../models/operations/index.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: operations.GetWorkspaceDocumentRequest$inboundSchema,
};

export const tool$workspaceDocumentsGetWorkspaceDocument: ToolDefinition<
  typeof args
> = {
  name: "workspace-documents-get-workspace-document",
  description: `Get information about the document

This operation retrieves information about the document. The response includes the document ID, name, and metadata.`,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await workspaceDocumentsGetWorkspaceDocument(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
