/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { ClientSDK } from "../lib/sdks.js";
import { WorkspaceDocuments } from "./workspacedocuments.js";
import { Workspaces } from "./workspaces.js";
import { WorkspaceUsers } from "./workspaceusers.js";

export class DocusignTypescriptTest2 extends ClientSDK {
  private _workspaceDocuments?: WorkspaceDocuments;
  get workspaceDocuments(): WorkspaceDocuments {
    return (this._workspaceDocuments ??= new WorkspaceDocuments(this._options));
  }

  private _workspaceUsers?: WorkspaceUsers;
  get workspaceUsers(): WorkspaceUsers {
    return (this._workspaceUsers ??= new WorkspaceUsers(this._options));
  }

  private _workspaces?: Workspaces;
  get workspaces(): Workspaces {
    return (this._workspaces ??= new Workspaces(this._options));
  }
}
